name: dialoguess
description: 'Welcome to "Dialoguess" - where every conversation is an adventure! Dive into a world where your words shape the story, and every choice matters. Perfect for players who love to explore vibrant worlds through engaging storytelling'
publish_to: 'none'
version: 0.2.3+5

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  velocity_x: 
  google_fonts:
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_native_splash:
  audioplayers: ^5.2.1
  share_plus: ^7.2.1
  confetti: ^0.7.0
  animated_flip_counter: ^0.2.6
  add_to_cart_animation: ^2.0.3
  google_mobile_ads: ^3.1.0
  logging: ^1.2.0
  provider: ^6.1.1
  in_app_purchase: ^3.1.11
  go_router: ^12.1.1
  flutter_inappwebview: ^5.8.0
  package_info_plus: ^4.2.0
  games_services: ^4.0.0
  flutter_signin_button: ^2.0.0

flutter_native_splash:
  color: "263238"
  image: assets/logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/animations/