// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeXnsjtlYsi8CPAFcs-LtS24Q_enesXDs',
    appId: '1:292418326021:web:0d3d6e072ac2bcfa52966c',
    messagingSenderId: '292418326021',
    projectId: 'fluttersociallogin-ff63d',
    authDomain: 'fluttersociallogin-ff63d.firebaseapp.com',
    storageBucket: 'fluttersociallogin-ff63d.appspot.com',
    measurementId: 'G-CDSKV3YN8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPBD4hIbXCQ4ci6ipc2iwuyPUTc6lpIY',
    appId: '1:292418326021:android:8391cb091ab6770352966c',
    messagingSenderId: '292418326021',
    projectId: 'fluttersociallogin-ff63d',
    storageBucket: 'fluttersociallogin-ff63d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAavMGh516x_-mbo7kSHHA87nAY9CUBWKA',
    appId: '1:292418326021:ios:138bc16a48a939d452966c',
    messagingSenderId: '292418326021',
    projectId: 'fluttersociallogin-ff63d',
    storageBucket: 'fluttersociallogin-ff63d.appspot.com',
    iosBundleId: 'com.heyidb.dialoguess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAavMGh516x_-mbo7kSHHA87nAY9CUBWKA',
    appId: '1:292418326021:ios:2610f047fee3bc5752966c',
    messagingSenderId: '292418326021',
    projectId: 'fluttersociallogin-ff63d',
    storageBucket: 'fluttersociallogin-ff63d.appspot.com',
    iosBundleId: 'com.example.dialoguess.RunnerTests',
  );
}
